// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package launch_template

import (
	"context"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.LaunchTemplate{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer exit(err)
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeLaunchTemplatesOutput
	resp, err = rm.sdkapi.DescribeLaunchTemplatesWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeLaunchTemplates", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.LaunchTemplates {
		if elem.LaunchTemplateName != nil {
			ko.Spec.LaunchTemplateName = elem.LaunchTemplateName
		} else {
			ko.Spec.LaunchTemplateName = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.LaunchTemplateName == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeLaunchTemplatesInput, error) {
	res := &svcsdk.DescribeLaunchTemplatesInput{}

	if r.ko.Spec.LaunchTemplateName != nil {
		f3 := []*string{}
		f3 = append(f3, r.ko.Spec.LaunchTemplateName)
		res.SetLaunchTemplateNames(f3)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer exit(err)
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateLaunchTemplateOutput
	_ = resp
	resp, err = rm.sdkapi.CreateLaunchTemplateWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateLaunchTemplate", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.LaunchTemplate != nil {
		f0 := &svcapitypes.LaunchTemplate_SDK{}
		if resp.LaunchTemplate.CreateTime != nil {
			f0.CreateTime = &metav1.Time{*resp.LaunchTemplate.CreateTime}
		}
		if resp.LaunchTemplate.CreatedBy != nil {
			f0.CreatedBy = resp.LaunchTemplate.CreatedBy
		}
		if resp.LaunchTemplate.DefaultVersionNumber != nil {
			f0.DefaultVersionNumber = resp.LaunchTemplate.DefaultVersionNumber
		}
		if resp.LaunchTemplate.LatestVersionNumber != nil {
			f0.LatestVersionNumber = resp.LaunchTemplate.LatestVersionNumber
		}
		if resp.LaunchTemplate.LaunchTemplateId != nil {
			f0.LaunchTemplateID = resp.LaunchTemplate.LaunchTemplateId
		}
		if resp.LaunchTemplate.LaunchTemplateName != nil {
			f0.LaunchTemplateName = resp.LaunchTemplate.LaunchTemplateName
		}
		if resp.LaunchTemplate.Tags != nil {
			f0f6 := []*svcapitypes.Tag{}
			for _, f0f6iter := range resp.LaunchTemplate.Tags {
				f0f6elem := &svcapitypes.Tag{}
				if f0f6iter.Key != nil {
					f0f6elem.Key = f0f6iter.Key
				}
				if f0f6iter.Value != nil {
					f0f6elem.Value = f0f6iter.Value
				}
				f0f6 = append(f0f6, f0f6elem)
			}
			f0.Tags = f0f6
		}
		ko.Status.LaunchTemplate = f0
	} else {
		ko.Status.LaunchTemplate = nil
	}
	if resp.Warning != nil {
		f1 := &svcapitypes.ValidationWarning{}
		if resp.Warning.Errors != nil {
			f1f0 := []*svcapitypes.ValidationError{}
			for _, f1f0iter := range resp.Warning.Errors {
				f1f0elem := &svcapitypes.ValidationError{}
				if f1f0iter.Code != nil {
					f1f0elem.Code = f1f0iter.Code
				}
				if f1f0iter.Message != nil {
					f1f0elem.Message = f1f0iter.Message
				}
				f1f0 = append(f1f0, f1f0elem)
			}
			f1.Errors = f1f0
		}
		ko.Status.Warning = f1
	} else {
		ko.Status.Warning = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateLaunchTemplateInput, error) {
	res := &svcsdk.CreateLaunchTemplateInput{}

	if r.ko.Spec.ClientToken != nil {
		res.SetClientToken(*r.ko.Spec.ClientToken)
	}
	if r.ko.Spec.LaunchTemplateData != nil {
		f1 := &svcsdk.RequestLaunchTemplateData{}
		if r.ko.Spec.LaunchTemplateData.BlockDeviceMappings != nil {
			f1f0 := []*svcsdk.LaunchTemplateBlockDeviceMappingRequest{}
			for _, f1f0iter := range r.ko.Spec.LaunchTemplateData.BlockDeviceMappings {
				f1f0elem := &svcsdk.LaunchTemplateBlockDeviceMappingRequest{}
				if f1f0iter.DeviceName != nil {
					f1f0elem.SetDeviceName(*f1f0iter.DeviceName)
				}
				if f1f0iter.EBS != nil {
					f1f0elemf1 := &svcsdk.LaunchTemplateEbsBlockDeviceRequest{}
					if f1f0iter.EBS.DeleteOnTermination != nil {
						f1f0elemf1.SetDeleteOnTermination(*f1f0iter.EBS.DeleteOnTermination)
					}
					if f1f0iter.EBS.Encrypted != nil {
						f1f0elemf1.SetEncrypted(*f1f0iter.EBS.Encrypted)
					}
					if f1f0iter.EBS.IOPS != nil {
						f1f0elemf1.SetIops(*f1f0iter.EBS.IOPS)
					}
					if f1f0iter.EBS.KMSKeyID != nil {
						f1f0elemf1.SetKmsKeyId(*f1f0iter.EBS.KMSKeyID)
					}
					if f1f0iter.EBS.SnapshotID != nil {
						f1f0elemf1.SetSnapshotId(*f1f0iter.EBS.SnapshotID)
					}
					if f1f0iter.EBS.Throughput != nil {
						f1f0elemf1.SetThroughput(*f1f0iter.EBS.Throughput)
					}
					if f1f0iter.EBS.VolumeSize != nil {
						f1f0elemf1.SetVolumeSize(*f1f0iter.EBS.VolumeSize)
					}
					if f1f0iter.EBS.VolumeType != nil {
						f1f0elemf1.SetVolumeType(*f1f0iter.EBS.VolumeType)
					}
					f1f0elem.SetEbs(f1f0elemf1)
				}
				if f1f0iter.NoDevice != nil {
					f1f0elem.SetNoDevice(*f1f0iter.NoDevice)
				}
				if f1f0iter.VirtualName != nil {
					f1f0elem.SetVirtualName(*f1f0iter.VirtualName)
				}
				f1f0 = append(f1f0, f1f0elem)
			}
			f1.SetBlockDeviceMappings(f1f0)
		}
		if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification != nil {
			f1f1 := &svcsdk.LaunchTemplateCapacityReservationSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference != nil {
				f1f1.SetCapacityReservationPreference(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference)
			}
			if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget != nil {
				f1f1f1 := &svcsdk.CapacityReservationTarget{}
				if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationID != nil {
					f1f1f1.SetCapacityReservationId(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationID)
				}
				if r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARN != nil {
					f1f1f1.SetCapacityReservationResourceGroupArn(*r.ko.Spec.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARN)
				}
				f1f1.SetCapacityReservationTarget(f1f1f1)
			}
			f1.SetCapacityReservationSpecification(f1f1)
		}
		if r.ko.Spec.LaunchTemplateData.CPUOptions != nil {
			f1f2 := &svcsdk.LaunchTemplateCpuOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.CPUOptions.CoreCount != nil {
				f1f2.SetCoreCount(*r.ko.Spec.LaunchTemplateData.CPUOptions.CoreCount)
			}
			if r.ko.Spec.LaunchTemplateData.CPUOptions.ThreadsPerCore != nil {
				f1f2.SetThreadsPerCore(*r.ko.Spec.LaunchTemplateData.CPUOptions.ThreadsPerCore)
			}
			f1.SetCpuOptions(f1f2)
		}
		if r.ko.Spec.LaunchTemplateData.CreditSpecification != nil {
			f1f3 := &svcsdk.CreditSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.CreditSpecification.CPUCredits != nil {
				f1f3.SetCpuCredits(*r.ko.Spec.LaunchTemplateData.CreditSpecification.CPUCredits)
			}
			f1.SetCreditSpecification(f1f3)
		}
		if r.ko.Spec.LaunchTemplateData.DisableAPITermination != nil {
			f1.SetDisableApiTermination(*r.ko.Spec.LaunchTemplateData.DisableAPITermination)
		}
		if r.ko.Spec.LaunchTemplateData.EBSOptimized != nil {
			f1.SetEbsOptimized(*r.ko.Spec.LaunchTemplateData.EBSOptimized)
		}
		if r.ko.Spec.LaunchTemplateData.ElasticGPUSpecifications != nil {
			f1f6 := []*svcsdk.ElasticGpuSpecification{}
			for _, f1f6iter := range r.ko.Spec.LaunchTemplateData.ElasticGPUSpecifications {
				f1f6elem := &svcsdk.ElasticGpuSpecification{}
				if f1f6iter.Type != nil {
					f1f6elem.SetType(*f1f6iter.Type)
				}
				f1f6 = append(f1f6, f1f6elem)
			}
			f1.SetElasticGpuSpecifications(f1f6)
		}
		if r.ko.Spec.LaunchTemplateData.ElasticInferenceAccelerators != nil {
			f1f7 := []*svcsdk.LaunchTemplateElasticInferenceAccelerator{}
			for _, f1f7iter := range r.ko.Spec.LaunchTemplateData.ElasticInferenceAccelerators {
				f1f7elem := &svcsdk.LaunchTemplateElasticInferenceAccelerator{}
				if f1f7iter.Count != nil {
					f1f7elem.SetCount(*f1f7iter.Count)
				}
				if f1f7iter.Type != nil {
					f1f7elem.SetType(*f1f7iter.Type)
				}
				f1f7 = append(f1f7, f1f7elem)
			}
			f1.SetElasticInferenceAccelerators(f1f7)
		}
		if r.ko.Spec.LaunchTemplateData.EnclaveOptions != nil {
			f1f8 := &svcsdk.LaunchTemplateEnclaveOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.EnclaveOptions.Enabled != nil {
				f1f8.SetEnabled(*r.ko.Spec.LaunchTemplateData.EnclaveOptions.Enabled)
			}
			f1.SetEnclaveOptions(f1f8)
		}
		if r.ko.Spec.LaunchTemplateData.HibernationOptions != nil {
			f1f9 := &svcsdk.LaunchTemplateHibernationOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.HibernationOptions.Configured != nil {
				f1f9.SetConfigured(*r.ko.Spec.LaunchTemplateData.HibernationOptions.Configured)
			}
			f1.SetHibernationOptions(f1f9)
		}
		if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile != nil {
			f1f10 := &svcsdk.LaunchTemplateIamInstanceProfileSpecificationRequest{}
			if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.ARN != nil {
				f1f10.SetArn(*r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.ARN)
			}
			if r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.Name != nil {
				f1f10.SetName(*r.ko.Spec.LaunchTemplateData.IAMInstanceProfile.Name)
			}
			f1.SetIamInstanceProfile(f1f10)
		}
		if r.ko.Spec.LaunchTemplateData.ImageID != nil {
			f1.SetImageId(*r.ko.Spec.LaunchTemplateData.ImageID)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceInitiatedShutdownBehavior != nil {
			f1.SetInstanceInitiatedShutdownBehavior(*r.ko.Spec.LaunchTemplateData.InstanceInitiatedShutdownBehavior)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions != nil {
			f1f13 := &svcsdk.LaunchTemplateInstanceMarketOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.MarketType != nil {
				f1f13.SetMarketType(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.MarketType)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions != nil {
				f1f13f1 := &svcsdk.LaunchTemplateSpotMarketOptionsRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes != nil {
					f1f13f1.SetBlockDurationMinutes(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior != nil {
					f1f13f1.SetInstanceInterruptionBehavior(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice != nil {
					f1f13f1.SetMaxPrice(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType != nil {
					f1f13f1.SetSpotInstanceType(*r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil != nil {
					f1f13f1.SetValidUntil(r.ko.Spec.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil.Time)
				}
				f1f13.SetSpotOptions(f1f13f1)
			}
			f1.SetInstanceMarketOptions(f1f13)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceRequirements != nil {
			f1f14 := &svcsdk.InstanceRequirementsRequest{}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorCount != nil {
				f1f14f0 := &svcsdk.AcceleratorCountRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Max != nil {
					f1f14f0.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Min != nil {
					f1f14f0.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Min)
				}
				f1f14.SetAcceleratorCount(f1f14f0)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorManufacturers != nil {
				f1f14f1 := []*string{}
				for _, f1f14f1iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorManufacturers {
					var f1f14f1elem string
					f1f14f1elem = *f1f14f1iter
					f1f14f1 = append(f1f14f1, &f1f14f1elem)
				}
				f1f14.SetAcceleratorManufacturers(f1f14f1)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorNames != nil {
				f1f14f2 := []*string{}
				for _, f1f14f2iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorNames {
					var f1f14f2elem string
					f1f14f2elem = *f1f14f2iter
					f1f14f2 = append(f1f14f2, &f1f14f2elem)
				}
				f1f14.SetAcceleratorNames(f1f14f2)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
				f1f14f3 := &svcsdk.AcceleratorTotalMemoryMiBRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
					f1f14f3.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
					f1f14f3.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
				}
				f1f14.SetAcceleratorTotalMemoryMiB(f1f14f3)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTypes != nil {
				f1f14f4 := []*string{}
				for _, f1f14f4iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.AcceleratorTypes {
					var f1f14f4elem string
					f1f14f4elem = *f1f14f4iter
					f1f14f4 = append(f1f14f4, &f1f14f4elem)
				}
				f1f14.SetAcceleratorTypes(f1f14f4)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.BareMetal != nil {
				f1f14.SetBareMetal(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.BareMetal)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
				f1f14f6 := &svcsdk.BaselineEbsBandwidthMbpsRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
					f1f14f6.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.BaselineEBSBandwidthMbps.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
					f1f14f6.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.BaselineEBSBandwidthMbps.Min)
				}
				f1f14.SetBaselineEbsBandwidthMbps(f1f14f6)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.BurstablePerformance != nil {
				f1f14.SetBurstablePerformance(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.BurstablePerformance)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.CPUManufacturers != nil {
				f1f14f8 := []*string{}
				for _, f1f14f8iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.CPUManufacturers {
					var f1f14f8elem string
					f1f14f8elem = *f1f14f8iter
					f1f14f8 = append(f1f14f8, &f1f14f8elem)
				}
				f1f14.SetCpuManufacturers(f1f14f8)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.ExcludedInstanceTypes != nil {
				f1f14f9 := []*string{}
				for _, f1f14f9iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.ExcludedInstanceTypes {
					var f1f14f9elem string
					f1f14f9elem = *f1f14f9iter
					f1f14f9 = append(f1f14f9, &f1f14f9elem)
				}
				f1f14.SetExcludedInstanceTypes(f1f14f9)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.InstanceGenerations != nil {
				f1f14f10 := []*string{}
				for _, f1f14f10iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.InstanceGenerations {
					var f1f14f10elem string
					f1f14f10elem = *f1f14f10iter
					f1f14f10 = append(f1f14f10, &f1f14f10elem)
				}
				f1f14.SetInstanceGenerations(f1f14f10)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.LocalStorage != nil {
				f1f14.SetLocalStorage(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.LocalStorage)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.LocalStorageTypes != nil {
				f1f14f12 := []*string{}
				for _, f1f14f12iter := range r.ko.Spec.LaunchTemplateData.InstanceRequirements.LocalStorageTypes {
					var f1f14f12elem string
					f1f14f12elem = *f1f14f12iter
					f1f14f12 = append(f1f14f12, &f1f14f12elem)
				}
				f1f14.SetLocalStorageTypes(f1f14f12)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCPU != nil {
				f1f14f13 := &svcsdk.MemoryGiBPerVCpuRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
					f1f14f13.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCPU.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
					f1f14f13.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCPU.Min)
				}
				f1f14.SetMemoryGiBPerVCpu(f1f14f13)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryMiB != nil {
				f1f14f14 := &svcsdk.MemoryMiBRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryMiB.Max != nil {
					f1f14f14.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryMiB.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryMiB.Min != nil {
					f1f14f14.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.MemoryMiB.Min)
				}
				f1f14.SetMemoryMiB(f1f14f14)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount != nil {
				f1f14f15 := &svcsdk.NetworkInterfaceCountRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Max != nil {
					f1f14f15.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Min != nil {
					f1f14f15.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Min)
				}
				f1f14.SetNetworkInterfaceCount(f1f14f15)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
				f1f14.SetOnDemandMaxPricePercentageOverLowestPrice(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.RequireHibernateSupport != nil {
				f1f14.SetRequireHibernateSupport(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.RequireHibernateSupport)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
				f1f14.SetSpotMaxPricePercentageOverLowestPrice(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB != nil {
				f1f14f19 := &svcsdk.TotalLocalStorageGBRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Max != nil {
					f1f14f19.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Min != nil {
					f1f14f19.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Min)
				}
				f1f14.SetTotalLocalStorageGB(f1f14f19)
			}
			if r.ko.Spec.LaunchTemplateData.InstanceRequirements.VCPUCount != nil {
				f1f14f20 := &svcsdk.VCpuCountRangeRequest{}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.VCPUCount.Max != nil {
					f1f14f20.SetMax(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.VCPUCount.Max)
				}
				if r.ko.Spec.LaunchTemplateData.InstanceRequirements.VCPUCount.Min != nil {
					f1f14f20.SetMin(*r.ko.Spec.LaunchTemplateData.InstanceRequirements.VCPUCount.Min)
				}
				f1f14.SetVCpuCount(f1f14f20)
			}
			f1.SetInstanceRequirements(f1f14)
		}
		if r.ko.Spec.LaunchTemplateData.InstanceType != nil {
			f1.SetInstanceType(*r.ko.Spec.LaunchTemplateData.InstanceType)
		}
		if r.ko.Spec.LaunchTemplateData.KernelID != nil {
			f1.SetKernelId(*r.ko.Spec.LaunchTemplateData.KernelID)
		}
		if r.ko.Spec.LaunchTemplateData.KeyName != nil {
			f1.SetKeyName(*r.ko.Spec.LaunchTemplateData.KeyName)
		}
		if r.ko.Spec.LaunchTemplateData.LicenseSpecifications != nil {
			f1f18 := []*svcsdk.LaunchTemplateLicenseConfigurationRequest{}
			for _, f1f18iter := range r.ko.Spec.LaunchTemplateData.LicenseSpecifications {
				f1f18elem := &svcsdk.LaunchTemplateLicenseConfigurationRequest{}
				if f1f18iter.LicenseConfigurationARN != nil {
					f1f18elem.SetLicenseConfigurationArn(*f1f18iter.LicenseConfigurationARN)
				}
				f1f18 = append(f1f18, f1f18elem)
			}
			f1.SetLicenseSpecifications(f1f18)
		}
		if r.ko.Spec.LaunchTemplateData.MetadataOptions != nil {
			f1f19 := &svcsdk.LaunchTemplateInstanceMetadataOptionsRequest{}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPEndpoint != nil {
				f1f19.SetHttpEndpoint(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPEndpoint)
			}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPProtocolIPv6 != nil {
				f1f19.SetHttpProtocolIpv6(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPProtocolIPv6)
			}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPPutResponseHopLimit != nil {
				f1f19.SetHttpPutResponseHopLimit(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPPutResponseHopLimit)
			}
			if r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPTokens != nil {
				f1f19.SetHttpTokens(*r.ko.Spec.LaunchTemplateData.MetadataOptions.HTTPTokens)
			}
			f1.SetMetadataOptions(f1f19)
		}
		if r.ko.Spec.LaunchTemplateData.Monitoring != nil {
			f1f20 := &svcsdk.LaunchTemplatesMonitoringRequest{}
			if r.ko.Spec.LaunchTemplateData.Monitoring.Enabled != nil {
				f1f20.SetEnabled(*r.ko.Spec.LaunchTemplateData.Monitoring.Enabled)
			}
			f1.SetMonitoring(f1f20)
		}
		if r.ko.Spec.LaunchTemplateData.NetworkInterfaces != nil {
			f1f21 := []*svcsdk.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
			for _, f1f21iter := range r.ko.Spec.LaunchTemplateData.NetworkInterfaces {
				f1f21elem := &svcsdk.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{}
				if f1f21iter.AssociateCarrierIPAddress != nil {
					f1f21elem.SetAssociateCarrierIpAddress(*f1f21iter.AssociateCarrierIPAddress)
				}
				if f1f21iter.AssociatePublicIPAddress != nil {
					f1f21elem.SetAssociatePublicIpAddress(*f1f21iter.AssociatePublicIPAddress)
				}
				if f1f21iter.DeleteOnTermination != nil {
					f1f21elem.SetDeleteOnTermination(*f1f21iter.DeleteOnTermination)
				}
				if f1f21iter.Description != nil {
					f1f21elem.SetDescription(*f1f21iter.Description)
				}
				if f1f21iter.DeviceIndex != nil {
					f1f21elem.SetDeviceIndex(*f1f21iter.DeviceIndex)
				}
				if f1f21iter.Groups != nil {
					f1f21elemf5 := []*string{}
					for _, f1f21elemf5iter := range f1f21iter.Groups {
						var f1f21elemf5elem string
						f1f21elemf5elem = *f1f21elemf5iter
						f1f21elemf5 = append(f1f21elemf5, &f1f21elemf5elem)
					}
					f1f21elem.SetGroups(f1f21elemf5)
				}
				if f1f21iter.InterfaceType != nil {
					f1f21elem.SetInterfaceType(*f1f21iter.InterfaceType)
				}
				if f1f21iter.IPv4PrefixCount != nil {
					f1f21elem.SetIpv4PrefixCount(*f1f21iter.IPv4PrefixCount)
				}
				if f1f21iter.IPv4Prefixes != nil {
					f1f21elemf8 := []*svcsdk.Ipv4PrefixSpecificationRequest{}
					for _, f1f21elemf8iter := range f1f21iter.IPv4Prefixes {
						f1f21elemf8elem := &svcsdk.Ipv4PrefixSpecificationRequest{}
						if f1f21elemf8iter.IPv4Prefix != nil {
							f1f21elemf8elem.SetIpv4Prefix(*f1f21elemf8iter.IPv4Prefix)
						}
						f1f21elemf8 = append(f1f21elemf8, f1f21elemf8elem)
					}
					f1f21elem.SetIpv4Prefixes(f1f21elemf8)
				}
				if f1f21iter.IPv6AddressCount != nil {
					f1f21elem.SetIpv6AddressCount(*f1f21iter.IPv6AddressCount)
				}
				if f1f21iter.IPv6Addresses != nil {
					f1f21elemf10 := []*svcsdk.InstanceIpv6AddressRequest{}
					for _, f1f21elemf10iter := range f1f21iter.IPv6Addresses {
						f1f21elemf10elem := &svcsdk.InstanceIpv6AddressRequest{}
						if f1f21elemf10iter.IPv6Address != nil {
							f1f21elemf10elem.SetIpv6Address(*f1f21elemf10iter.IPv6Address)
						}
						f1f21elemf10 = append(f1f21elemf10, f1f21elemf10elem)
					}
					f1f21elem.SetIpv6Addresses(f1f21elemf10)
				}
				if f1f21iter.IPv6PrefixCount != nil {
					f1f21elem.SetIpv6PrefixCount(*f1f21iter.IPv6PrefixCount)
				}
				if f1f21iter.IPv6Prefixes != nil {
					f1f21elemf12 := []*svcsdk.Ipv6PrefixSpecificationRequest{}
					for _, f1f21elemf12iter := range f1f21iter.IPv6Prefixes {
						f1f21elemf12elem := &svcsdk.Ipv6PrefixSpecificationRequest{}
						if f1f21elemf12iter.IPv6Prefix != nil {
							f1f21elemf12elem.SetIpv6Prefix(*f1f21elemf12iter.IPv6Prefix)
						}
						f1f21elemf12 = append(f1f21elemf12, f1f21elemf12elem)
					}
					f1f21elem.SetIpv6Prefixes(f1f21elemf12)
				}
				if f1f21iter.NetworkCardIndex != nil {
					f1f21elem.SetNetworkCardIndex(*f1f21iter.NetworkCardIndex)
				}
				if f1f21iter.NetworkInterfaceID != nil {
					f1f21elem.SetNetworkInterfaceId(*f1f21iter.NetworkInterfaceID)
				}
				if f1f21iter.PrivateIPAddress != nil {
					f1f21elem.SetPrivateIpAddress(*f1f21iter.PrivateIPAddress)
				}
				if f1f21iter.PrivateIPAddresses != nil {
					f1f21elemf16 := []*svcsdk.PrivateIpAddressSpecification{}
					for _, f1f21elemf16iter := range f1f21iter.PrivateIPAddresses {
						f1f21elemf16elem := &svcsdk.PrivateIpAddressSpecification{}
						if f1f21elemf16iter.Primary != nil {
							f1f21elemf16elem.SetPrimary(*f1f21elemf16iter.Primary)
						}
						if f1f21elemf16iter.PrivateIPAddress != nil {
							f1f21elemf16elem.SetPrivateIpAddress(*f1f21elemf16iter.PrivateIPAddress)
						}
						f1f21elemf16 = append(f1f21elemf16, f1f21elemf16elem)
					}
					f1f21elem.SetPrivateIpAddresses(f1f21elemf16)
				}
				if f1f21iter.SecondaryPrivateIPAddressCount != nil {
					f1f21elem.SetSecondaryPrivateIpAddressCount(*f1f21iter.SecondaryPrivateIPAddressCount)
				}
				if f1f21iter.SubnetID != nil {
					f1f21elem.SetSubnetId(*f1f21iter.SubnetID)
				}
				f1f21 = append(f1f21, f1f21elem)
			}
			f1.SetNetworkInterfaces(f1f21)
		}
		if r.ko.Spec.LaunchTemplateData.Placement != nil {
			f1f22 := &svcsdk.LaunchTemplatePlacementRequest{}
			if r.ko.Spec.LaunchTemplateData.Placement.Affinity != nil {
				f1f22.SetAffinity(*r.ko.Spec.LaunchTemplateData.Placement.Affinity)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.AvailabilityZone != nil {
				f1f22.SetAvailabilityZone(*r.ko.Spec.LaunchTemplateData.Placement.AvailabilityZone)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.GroupName != nil {
				f1f22.SetGroupName(*r.ko.Spec.LaunchTemplateData.Placement.GroupName)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.HostID != nil {
				f1f22.SetHostId(*r.ko.Spec.LaunchTemplateData.Placement.HostID)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.HostResourceGroupARN != nil {
				f1f22.SetHostResourceGroupArn(*r.ko.Spec.LaunchTemplateData.Placement.HostResourceGroupARN)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.PartitionNumber != nil {
				f1f22.SetPartitionNumber(*r.ko.Spec.LaunchTemplateData.Placement.PartitionNumber)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.SpreadDomain != nil {
				f1f22.SetSpreadDomain(*r.ko.Spec.LaunchTemplateData.Placement.SpreadDomain)
			}
			if r.ko.Spec.LaunchTemplateData.Placement.Tenancy != nil {
				f1f22.SetTenancy(*r.ko.Spec.LaunchTemplateData.Placement.Tenancy)
			}
			f1.SetPlacement(f1f22)
		}
		if r.ko.Spec.LaunchTemplateData.RamDiskID != nil {
			f1.SetRamDiskId(*r.ko.Spec.LaunchTemplateData.RamDiskID)
		}
		if r.ko.Spec.LaunchTemplateData.SecurityGroupIDs != nil {
			f1f24 := []*string{}
			for _, f1f24iter := range r.ko.Spec.LaunchTemplateData.SecurityGroupIDs {
				var f1f24elem string
				f1f24elem = *f1f24iter
				f1f24 = append(f1f24, &f1f24elem)
			}
			f1.SetSecurityGroupIds(f1f24)
		}
		if r.ko.Spec.LaunchTemplateData.SecurityGroups != nil {
			f1f25 := []*string{}
			for _, f1f25iter := range r.ko.Spec.LaunchTemplateData.SecurityGroups {
				var f1f25elem string
				f1f25elem = *f1f25iter
				f1f25 = append(f1f25, &f1f25elem)
			}
			f1.SetSecurityGroups(f1f25)
		}
		if r.ko.Spec.LaunchTemplateData.TagSpecifications != nil {
			f1f26 := []*svcsdk.LaunchTemplateTagSpecificationRequest{}
			for _, f1f26iter := range r.ko.Spec.LaunchTemplateData.TagSpecifications {
				f1f26elem := &svcsdk.LaunchTemplateTagSpecificationRequest{}
				if f1f26iter.ResourceType != nil {
					f1f26elem.SetResourceType(*f1f26iter.ResourceType)
				}
				if f1f26iter.Tags != nil {
					f1f26elemf1 := []*svcsdk.Tag{}
					for _, f1f26elemf1iter := range f1f26iter.Tags {
						f1f26elemf1elem := &svcsdk.Tag{}
						if f1f26elemf1iter.Key != nil {
							f1f26elemf1elem.SetKey(*f1f26elemf1iter.Key)
						}
						if f1f26elemf1iter.Value != nil {
							f1f26elemf1elem.SetValue(*f1f26elemf1iter.Value)
						}
						f1f26elemf1 = append(f1f26elemf1, f1f26elemf1elem)
					}
					f1f26elem.SetTags(f1f26elemf1)
				}
				f1f26 = append(f1f26, f1f26elem)
			}
			f1.SetTagSpecifications(f1f26)
		}
		if r.ko.Spec.LaunchTemplateData.UserData != nil {
			f1.SetUserData(*r.ko.Spec.LaunchTemplateData.UserData)
		}
		res.SetLaunchTemplateData(f1)
	}
	if r.ko.Spec.LaunchTemplateName != nil {
		res.SetLaunchTemplateName(*r.ko.Spec.LaunchTemplateName)
	}
	if r.ko.Spec.TagSpecifications != nil {
		f3 := []*svcsdk.TagSpecification{}
		for _, f3iter := range r.ko.Spec.TagSpecifications {
			f3elem := &svcsdk.TagSpecification{}
			if f3iter.ResourceType != nil {
				f3elem.SetResourceType(*f3iter.ResourceType)
			}
			if f3iter.Tags != nil {
				f3elemf1 := []*svcsdk.Tag{}
				for _, f3elemf1iter := range f3iter.Tags {
					f3elemf1elem := &svcsdk.Tag{}
					if f3elemf1iter.Key != nil {
						f3elemf1elem.SetKey(*f3elemf1iter.Key)
					}
					if f3elemf1iter.Value != nil {
						f3elemf1elem.SetValue(*f3elemf1iter.Value)
					}
					f3elemf1 = append(f3elemf1, f3elemf1elem)
				}
				f3elem.SetTags(f3elemf1)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTagSpecifications(f3)
	}
	if r.ko.Spec.VersionDescription != nil {
		res.SetVersionDescription(*r.ko.Spec.VersionDescription)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer exit(err)
	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyLaunchTemplateOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyLaunchTemplateWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyLaunchTemplate", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.LaunchTemplate.LaunchTemplateName != nil {
		ko.Spec.LaunchTemplateName = resp.LaunchTemplate.LaunchTemplateName
	} else {
		ko.Spec.LaunchTemplateName = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyLaunchTemplateInput, error) {
	res := &svcsdk.ModifyLaunchTemplateInput{}

	if r.ko.Spec.ClientToken != nil {
		res.SetClientToken(*r.ko.Spec.ClientToken)
	}
	if r.ko.Spec.LaunchTemplateName != nil {
		res.SetLaunchTemplateName(*r.ko.Spec.LaunchTemplateName)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer exit(err)
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteLaunchTemplateOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteLaunchTemplateWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteLaunchTemplate", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteLaunchTemplateInput, error) {
	res := &svcsdk.DeleteLaunchTemplateInput{}

	if r.ko.Spec.LaunchTemplateName != nil {
		res.SetLaunchTemplateName(*r.ko.Spec.LaunchTemplateName)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.LaunchTemplate,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}

	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
